package model.pojo;
// Generated Mar 19, 2019 1:11:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Long id;
     private Date createdAt;
     private String designation;
     private String name;

    public Employees() {
    }

	
    public Employees(String designation, String name) {
        this.designation = designation;
        this.name = name;
    }
    public Employees(Date createdAt, String designation, String name) {
       this.createdAt = createdAt;
       this.designation = designation;
       this.name = name;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


