package model.pojo;
// Generated Mar 19, 2019 1:11:11 PM by Hibernate Tools 4.3.1



/**
 * EmployeesContact generated by hbm2java
 */
public class EmployeesContact  implements java.io.Serializable {


     private Long id;
     private String email;
     private String employeeId;
     private String phone;

    public EmployeesContact() {
    }

    public EmployeesContact(String email, String employeeId, String phone) {
       this.email = email;
       this.employeeId = employeeId;
       this.phone = phone;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


